from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


def create_draft(*, to: str | None = None, cc: str | None = None, subject: str | None = None, body: str | None = None) -> dict[str, Any]:
    """Create an Outlook draft message without sending it."""
    try:
        import win32com.client as win32
    except ImportError as exc:
        logger.exception("pywin32 is required to create Outlook drafts")
        return {"success": False, "error": "pywin32 is required to access Outlook via COM."}

    try:
        outlook = win32.Dispatch("Outlook.Application")
        mail = outlook.CreateItem(0)
        mail.To = to or ""
        mail.CC = cc or ""
        mail.Subject = subject or ""
        mail.Body = body or ""
        mail.Save()
        logger.info("Created Outlook draft for subject %s", subject)
        return {"success": True, "draft_id": getattr(mail, "EntryID", None)}
    except Exception as exc:
        logger.exception("Failed to create Outlook draft")
        return {"success": False, "error": str(exc)}


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    print("Connecting to Outlook...")
    result = create_draft(
        subject="TEST - VisualCron AI Agent",
        body="This is a test draft generated by VisualCron AI Support Agent.",
    )
    if result.get("success"):
        print("Creating Draft...")
        print("Draft Created Successfully.")
    else:
        print(f"Draft creation failed: {result.get('error')}")
